### PR TITLE
[fix] make puppet-itchat great again

### PR DESCRIPTION
**Pull request by ly1ex**
* change UOS_PATCH_EXTSPAM
* change `skey` and `pass_ticket` in login_info

### CODE REVIEW

**Comment by bigbrother666sh** [comment]
hey… how about the PR. 
It seems check error just caused by gfw... not the code itself.

Look farword to the puppet great again.. and if there's anything I could help, glad to do!

**Comment by wj-Mcat** [comment]
Please make CI green so that we can merge this pr, and make puppt-itchat great again.

**Comment by wj-Mcat** [comment]
There are some conflicts, can you fix it to make it great again ?

**Comment by bigbrother666sh** [comment]
一个不幸的消息……貌似这个版本也没有办法再用了。
现在uos扫码登录后，客户端点确定后会有倒数5s的风险提示，也没法消掉，导致wechaty这边log in time out。。。
```
2022-08-30 15:56:20,011 - Wechaty - INFO - or you can scan qrcode from: https://wechaty.js.org/qrcode/https://login.weixin.qq.com/l/gbI69MT4eg==
2022-08-30 15:56:20,011 - Wechaty - ERROR - internal error <>
2022-08-30 15:56:23,376 - Wechaty - INFO - receive <scan> event <EventScanPayload(status=<ScanStatus.Cancel: 1>, qrcode='https://login.weixin.qq.com/l/gbI69MT4eg==', data=None)>
2022-08-30 15:56:23,376 - Wechaty - ERROR - internal error <>
Log in time out, reloading QR code.
2022-08-30 15:56:23,476 - Wechaty - INFO - receive <scan> event <EventScanPayload(status=<ScanStatus.Timeout: 5>, qrcode='https://login.weixin.qq.com/l/gbI69MT4eg==', data=None)>
2022-08-30 15:56:23,477 - Wechaty - ERROR - internal error <>
Getting uuid of QR code.
https://wechaty.js.org/qrcode/https://login.weixin.qq.com/l/ofgXSXuFRA==
2022-08-30 15:56:23,648 - Wechaty - INFO - receive <scan> event <EventScanPayload(status=<ScanStatus.Waiting: 2>, qrcode='https://login.weixin.qq.com/l/ofgXSXuFRA==', data=None)>
```
我试过了0.6.4~0.8.66多个版本的wechaty都这样。
puppet 也试过0.2.1版本

**Comment by wj-Mcat** [comment]
Closed by inactive

**Pull request closed without merging**
